//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    using Param;

    public partial class Item
    {
        public int Id { get; set; }
        public int Supplier_Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int Stock { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Supplier Supplier { get; set; }

        public Item() { }
        public Item(ItemParam itemparam)
        {
            this.Name = itemparam.Name;
            this.Price = itemparam.Price;
            this.Stock = itemparam.Stock;
            this.IsDelete = false;
            this.CreateDate = DateTimeOffset.Now.LocalDateTime;
        }

        public void Update(ItemParam itemparam)
        {
            this.Name = itemparam.Name;
            this.Price = itemparam.Price;
            this.Stock = itemparam.Stock;
            this.UpdateDate = DateTimeOffset.Now.LocalDateTime;
        }
        public void Delete(ItemParam itemparam)
        {
            this.IsDelete = false;
            this.DeleteDate = DateTimeOffset.Now.LocalDateTime;
        }
    }
}
